# Generated by Django 6.0.1 on 2026-01-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='system_instructions',
            field=models.TextField(
                blank=True,
                default="",
                help_text='System instructions used to initialize the interaction',
            ),
        ),
    ]
